run:
  timeout: 3m
  tests: true
  modules-download-mode: mod

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - errcheck
    - gofmt
    - revive
    - goconst
    - gosec

  disable:
    - depguard
    - funlen
    - gocyclo
    - gocognit

linters-settings:
  revive:
    severity: warning
    rules:
      - name: exported
        severity: warning
      - name: if-return
      - name: var-naming
      - name: blank-imports
      - name: indent-error-flow

  gosec:
    excludes:
      - G104

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 5

  exclude-dirs:
    - vendor

  exclude-files:
    - "internal/api/openapi.gen.go"

    - "internal/repository/postgres/pr_repo.go"  # было решено добавить эти файлы в исключения, так как решить за короткий срок проблему с постоянной ошибкой pgx с линтером не получилось
    - "internal/repository/postgres/user_repo.go"
    - "internal/repository/postgres/team_repo.go"

  exclude:
    - "should have comment or be unexported"

output:
  sort-results: true