//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for ErrorResponseErrorCode.
const (
	NOCANDIDATE ErrorResponseErrorCode = "NO_CANDIDATE"
	NOTASSIGNED ErrorResponseErrorCode = "NOT_ASSIGNED"
	NOTFOUND    ErrorResponseErrorCode = "NOT_FOUND"
	PREXISTS    ErrorResponseErrorCode = "PR_EXISTS"
	PRMERGED    ErrorResponseErrorCode = "PR_MERGED"
	TEAMEXISTS  ErrorResponseErrorCode = "TEAM_EXISTS"
)

// Defines values for PullRequestStatus.
const (
	PullRequestStatusMERGED PullRequestStatus = "MERGED"
	PullRequestStatusOPEN   PullRequestStatus = "OPEN"
)

// Defines values for PullRequestShortStatus.
const (
	PullRequestShortStatusMERGED PullRequestShortStatus = "MERGED"
	PullRequestShortStatusOPEN   PullRequestShortStatus = "OPEN"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    ErrorResponseErrorCode `json:"code"`
		Message string                 `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode defines model for ErrorResponse.Error.Code.
type ErrorResponseErrorCode string

// MassDeactivateRequest defines model for MassDeactivateRequest.
type MassDeactivateRequest struct {
	// TeamName Имя команды, в которой нужно деактивировать пользователей
	TeamName string `json:"team_name"`

	// UserIds Список идентификаторов пользователей для деактивации
	UserIds []string `json:"user_ids"`
}

// MassDeactivateResult defines model for MassDeactivateResult.
type MassDeactivateResult struct {
	// DeactivatedCount Количество успешно деактивированных пользователей
	DeactivatedCount int `json:"deactivated_count"`

	// NotReassignedCount Количество PR, где заменить ревьюеров не удалось
	NotReassignedCount int `json:"not_reassigned_count"`

	// ReassignedCount Количество PR, где удалось безопасно переназначить ревьюеров
	ReassignedCount int `json:"reassigned_count"`
}

// PullRequest defines model for PullRequest.
type PullRequest struct {
	// AssignedReviewers user_id назначенных ревьюверов (0..2)
	AssignedReviewers []string          `json:"assigned_reviewers"`
	AuthorId          string            `json:"author_id"`
	CreatedAt         *time.Time        `json:"createdAt"`
	MergedAt          *time.Time        `json:"mergedAt"`
	PullRequestId     string            `json:"pull_request_id"`
	PullRequestName   string            `json:"pull_request_name"`
	Status            PullRequestStatus `json:"status"`
}

// PullRequestStatus defines model for PullRequest.Status.
type PullRequestStatus string

// PullRequestShort defines model for PullRequestShort.
type PullRequestShort struct {
	AuthorId        string                 `json:"author_id"`
	PullRequestId   string                 `json:"pull_request_id"`
	PullRequestName string                 `json:"pull_request_name"`
	Status          PullRequestShortStatus `json:"status"`
}

// PullRequestShortStatus defines model for PullRequestShort.Status.
type PullRequestShortStatus string

// ReviewerStat defines model for ReviewerStat.
type ReviewerStat struct {
	AssignedCount int64  `json:"assigned_count"`
	UserId        string `json:"user_id"`
}

// Team defines model for Team.
type Team struct {
	Members  []TeamMember `json:"members"`
	TeamName string       `json:"team_name"`
}

// TeamMember defines model for TeamMember.
type TeamMember struct {
	IsActive bool   `json:"is_active"`
	UserId   string `json:"user_id"`
	Username string `json:"username"`
}

// User defines model for User.
type User struct {
	IsActive bool   `json:"is_active"`
	TeamName string `json:"team_name"`
	UserId   string `json:"user_id"`
	Username string `json:"username"`
}

// TeamNameQuery defines model for TeamNameQuery.
type TeamNameQuery = string

// UserIdQuery defines model for UserIdQuery.
type UserIdQuery = string

// PostPullRequestCreateJSONBody defines parameters for PostPullRequestCreate.
type PostPullRequestCreateJSONBody struct {
	AuthorId        string `json:"author_id"`
	PullRequestId   string `json:"pull_request_id"`
	PullRequestName string `json:"pull_request_name"`
}

// PostPullRequestMergeJSONBody defines parameters for PostPullRequestMerge.
type PostPullRequestMergeJSONBody struct {
	PullRequestId string `json:"pull_request_id"`
}

// PostPullRequestReassignJSONBody defines parameters for PostPullRequestReassign.
type PostPullRequestReassignJSONBody struct {
	OldUserId     string `json:"old_user_id"`
	PullRequestId string `json:"pull_request_id"`
}

// GetTeamGetParams defines parameters for GetTeamGet.
type GetTeamGetParams struct {
	// TeamName Уникальное имя команды
	TeamName TeamNameQuery `form:"team_name" json:"team_name"`
}

// GetUsersGetReviewParams defines parameters for GetUsersGetReview.
type GetUsersGetReviewParams struct {
	// UserId Идентификатор пользователя
	UserId UserIdQuery `form:"user_id" json:"user_id"`
}

// PostUsersSetIsActiveJSONBody defines parameters for PostUsersSetIsActive.
type PostUsersSetIsActiveJSONBody struct {
	IsActive bool   `json:"is_active"`
	UserId   string `json:"user_id"`
}

// PostPullRequestCreateJSONRequestBody defines body for PostPullRequestCreate for application/json ContentType.
type PostPullRequestCreateJSONRequestBody PostPullRequestCreateJSONBody

// PostPullRequestMergeJSONRequestBody defines body for PostPullRequestMerge for application/json ContentType.
type PostPullRequestMergeJSONRequestBody PostPullRequestMergeJSONBody

// PostPullRequestReassignJSONRequestBody defines body for PostPullRequestReassign for application/json ContentType.
type PostPullRequestReassignJSONRequestBody PostPullRequestReassignJSONBody

// PostTeamAddJSONRequestBody defines body for PostTeamAdd for application/json ContentType.
type PostTeamAddJSONRequestBody = Team

// PostTeamMassDeactivateJSONRequestBody defines body for PostTeamMassDeactivate for application/json ContentType.
type PostTeamMassDeactivateJSONRequestBody = MassDeactivateRequest

// PostUsersSetIsActiveJSONRequestBody defines body for PostUsersSetIsActive for application/json ContentType.
type PostUsersSetIsActiveJSONRequestBody PostUsersSetIsActiveJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Создать PR и автоматически назначить до 2 ревьюверов из команды автора
	// (POST /pullRequest/create)
	PostPullRequestCreate(w http.ResponseWriter, r *http.Request)
	// Пометить PR как MERGED (идемпотентная операция)
	// (POST /pullRequest/merge)
	PostPullRequestMerge(w http.ResponseWriter, r *http.Request)
	// Переназначить конкретного ревьювера на другого из его команды
	// (POST /pullRequest/reassign)
	PostPullRequestReassign(w http.ResponseWriter, r *http.Request)
	// Получить количество назначений ревью по пользователям
	// (GET /stats/reviewerAssignments)
	GetStatsReviewerAssignments(w http.ResponseWriter, r *http.Request)
	// Создать команду с участниками (создаёт/обновляет пользователей)
	// (POST /team/add)
	PostTeamAdd(w http.ResponseWriter, r *http.Request)
	// Получить команду с участниками
	// (GET /team/get)
	GetTeamGet(w http.ResponseWriter, r *http.Request, params GetTeamGetParams)
	// Массово деактивировать пользователей команды и безопасно переназначить открытые PR
	// (POST /team/massDeactivate)
	PostTeamMassDeactivate(w http.ResponseWriter, r *http.Request)
	// Получить PR'ы, где пользователь назначен ревьювером
	// (GET /users/getReview)
	GetUsersGetReview(w http.ResponseWriter, r *http.Request, params GetUsersGetReviewParams)
	// Установить флаг активности пользователя
	// (POST /users/setIsActive)
	PostUsersSetIsActive(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostPullRequestCreate operation middleware
func (siw *ServerInterfaceWrapper) PostPullRequestCreate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPullRequestCreate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostPullRequestMerge operation middleware
func (siw *ServerInterfaceWrapper) PostPullRequestMerge(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPullRequestMerge(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostPullRequestReassign operation middleware
func (siw *ServerInterfaceWrapper) PostPullRequestReassign(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPullRequestReassign(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatsReviewerAssignments operation middleware
func (siw *ServerInterfaceWrapper) GetStatsReviewerAssignments(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatsReviewerAssignments(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTeamAdd operation middleware
func (siw *ServerInterfaceWrapper) PostTeamAdd(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTeamAdd(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTeamGet operation middleware
func (siw *ServerInterfaceWrapper) GetTeamGet(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTeamGetParams

	// ------------- Required query parameter "team_name" -------------

	if paramValue := r.URL.Query().Get("team_name"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "team_name"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "team_name", r.URL.Query(), &params.TeamName)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "team_name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTeamGet(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTeamMassDeactivate operation middleware
func (siw *ServerInterfaceWrapper) PostTeamMassDeactivate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTeamMassDeactivate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsersGetReview operation middleware
func (siw *ServerInterfaceWrapper) GetUsersGetReview(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersGetReviewParams

	// ------------- Required query parameter "user_id" -------------

	if paramValue := r.URL.Query().Get("user_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "user_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "user_id", r.URL.Query(), &params.UserId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsersGetReview(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUsersSetIsActive operation middleware
func (siw *ServerInterfaceWrapper) PostUsersSetIsActive(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsersSetIsActive(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/pullRequest/create", wrapper.PostPullRequestCreate)
	m.HandleFunc("POST "+options.BaseURL+"/pullRequest/merge", wrapper.PostPullRequestMerge)
	m.HandleFunc("POST "+options.BaseURL+"/pullRequest/reassign", wrapper.PostPullRequestReassign)
	m.HandleFunc("GET "+options.BaseURL+"/stats/reviewerAssignments", wrapper.GetStatsReviewerAssignments)
	m.HandleFunc("POST "+options.BaseURL+"/team/add", wrapper.PostTeamAdd)
	m.HandleFunc("GET "+options.BaseURL+"/team/get", wrapper.GetTeamGet)
	m.HandleFunc("POST "+options.BaseURL+"/team/massDeactivate", wrapper.PostTeamMassDeactivate)
	m.HandleFunc("GET "+options.BaseURL+"/users/getReview", wrapper.GetUsersGetReview)
	m.HandleFunc("POST "+options.BaseURL+"/users/setIsActive", wrapper.PostUsersSetIsActive)

	return m
}

type PostPullRequestCreateRequestObject struct {
	Body *PostPullRequestCreateJSONRequestBody
}

type PostPullRequestCreateResponseObject interface {
	VisitPostPullRequestCreateResponse(w http.ResponseWriter) error
}

type PostPullRequestCreate201JSONResponse struct {
	Pr *PullRequest `json:"pr,omitempty"`
}

func (response PostPullRequestCreate201JSONResponse) VisitPostPullRequestCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostPullRequestCreate404JSONResponse ErrorResponse

func (response PostPullRequestCreate404JSONResponse) VisitPostPullRequestCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostPullRequestCreate409JSONResponse ErrorResponse

func (response PostPullRequestCreate409JSONResponse) VisitPostPullRequestCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PostPullRequestMergeRequestObject struct {
	Body *PostPullRequestMergeJSONRequestBody
}

type PostPullRequestMergeResponseObject interface {
	VisitPostPullRequestMergeResponse(w http.ResponseWriter) error
}

type PostPullRequestMerge200JSONResponse struct {
	Pr *PullRequest `json:"pr,omitempty"`
}

func (response PostPullRequestMerge200JSONResponse) VisitPostPullRequestMergeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostPullRequestMerge404JSONResponse ErrorResponse

func (response PostPullRequestMerge404JSONResponse) VisitPostPullRequestMergeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostPullRequestReassignRequestObject struct {
	Body *PostPullRequestReassignJSONRequestBody
}

type PostPullRequestReassignResponseObject interface {
	VisitPostPullRequestReassignResponse(w http.ResponseWriter) error
}

type PostPullRequestReassign200JSONResponse struct {
	Pr PullRequest `json:"pr"`

	// ReplacedBy user_id нового ревьювера
	ReplacedBy string `json:"replaced_by"`
}

func (response PostPullRequestReassign200JSONResponse) VisitPostPullRequestReassignResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostPullRequestReassign404JSONResponse ErrorResponse

func (response PostPullRequestReassign404JSONResponse) VisitPostPullRequestReassignResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostPullRequestReassign409JSONResponse ErrorResponse

func (response PostPullRequestReassign409JSONResponse) VisitPostPullRequestReassignResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetStatsReviewerAssignmentsRequestObject struct {
}

type GetStatsReviewerAssignmentsResponseObject interface {
	VisitGetStatsReviewerAssignmentsResponse(w http.ResponseWriter) error
}

type GetStatsReviewerAssignments200JSONResponse struct {
	Stats []ReviewerStat `json:"stats"`
}

func (response GetStatsReviewerAssignments200JSONResponse) VisitGetStatsReviewerAssignmentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostTeamAddRequestObject struct {
	Body *PostTeamAddJSONRequestBody
}

type PostTeamAddResponseObject interface {
	VisitPostTeamAddResponse(w http.ResponseWriter) error
}

type PostTeamAdd201JSONResponse struct {
	Team *Team `json:"team,omitempty"`
}

func (response PostTeamAdd201JSONResponse) VisitPostTeamAddResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostTeamAdd400JSONResponse ErrorResponse

func (response PostTeamAdd400JSONResponse) VisitPostTeamAddResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetTeamGetRequestObject struct {
	Params GetTeamGetParams
}

type GetTeamGetResponseObject interface {
	VisitGetTeamGetResponse(w http.ResponseWriter) error
}

type GetTeamGet200JSONResponse Team

func (response GetTeamGet200JSONResponse) VisitGetTeamGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTeamGet404JSONResponse ErrorResponse

func (response GetTeamGet404JSONResponse) VisitGetTeamGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostTeamMassDeactivateRequestObject struct {
	Body *PostTeamMassDeactivateJSONRequestBody
}

type PostTeamMassDeactivateResponseObject interface {
	VisitPostTeamMassDeactivateResponse(w http.ResponseWriter) error
}

type PostTeamMassDeactivate200JSONResponse struct {
	Result *MassDeactivateResult `json:"result,omitempty"`
}

func (response PostTeamMassDeactivate200JSONResponse) VisitPostTeamMassDeactivateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostTeamMassDeactivate401JSONResponse ErrorResponse

func (response PostTeamMassDeactivate401JSONResponse) VisitPostTeamMassDeactivateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostTeamMassDeactivate404JSONResponse ErrorResponse

func (response PostTeamMassDeactivate404JSONResponse) VisitPostTeamMassDeactivateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersGetReviewRequestObject struct {
	Params GetUsersGetReviewParams
}

type GetUsersGetReviewResponseObject interface {
	VisitGetUsersGetReviewResponse(w http.ResponseWriter) error
}

type GetUsersGetReview200JSONResponse struct {
	PullRequests []PullRequestShort `json:"pull_requests"`
	UserId       string             `json:"user_id"`
}

func (response GetUsersGetReview200JSONResponse) VisitGetUsersGetReviewResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersSetIsActiveRequestObject struct {
	Body *PostUsersSetIsActiveJSONRequestBody
}

type PostUsersSetIsActiveResponseObject interface {
	VisitPostUsersSetIsActiveResponse(w http.ResponseWriter) error
}

type PostUsersSetIsActive200JSONResponse struct {
	User *User `json:"user,omitempty"`
}

func (response PostUsersSetIsActive200JSONResponse) VisitPostUsersSetIsActiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersSetIsActive401JSONResponse ErrorResponse

func (response PostUsersSetIsActive401JSONResponse) VisitPostUsersSetIsActiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersSetIsActive404JSONResponse ErrorResponse

func (response PostUsersSetIsActive404JSONResponse) VisitPostUsersSetIsActiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Создать PR и автоматически назначить до 2 ревьюверов из команды автора
	// (POST /pullRequest/create)
	PostPullRequestCreate(ctx context.Context, request PostPullRequestCreateRequestObject) (PostPullRequestCreateResponseObject, error)
	// Пометить PR как MERGED (идемпотентная операция)
	// (POST /pullRequest/merge)
	PostPullRequestMerge(ctx context.Context, request PostPullRequestMergeRequestObject) (PostPullRequestMergeResponseObject, error)
	// Переназначить конкретного ревьювера на другого из его команды
	// (POST /pullRequest/reassign)
	PostPullRequestReassign(ctx context.Context, request PostPullRequestReassignRequestObject) (PostPullRequestReassignResponseObject, error)
	// Получить количество назначений ревью по пользователям
	// (GET /stats/reviewerAssignments)
	GetStatsReviewerAssignments(ctx context.Context, request GetStatsReviewerAssignmentsRequestObject) (GetStatsReviewerAssignmentsResponseObject, error)
	// Создать команду с участниками (создаёт/обновляет пользователей)
	// (POST /team/add)
	PostTeamAdd(ctx context.Context, request PostTeamAddRequestObject) (PostTeamAddResponseObject, error)
	// Получить команду с участниками
	// (GET /team/get)
	GetTeamGet(ctx context.Context, request GetTeamGetRequestObject) (GetTeamGetResponseObject, error)
	// Массово деактивировать пользователей команды и безопасно переназначить открытые PR
	// (POST /team/massDeactivate)
	PostTeamMassDeactivate(ctx context.Context, request PostTeamMassDeactivateRequestObject) (PostTeamMassDeactivateResponseObject, error)
	// Получить PR'ы, где пользователь назначен ревьювером
	// (GET /users/getReview)
	GetUsersGetReview(ctx context.Context, request GetUsersGetReviewRequestObject) (GetUsersGetReviewResponseObject, error)
	// Установить флаг активности пользователя
	// (POST /users/setIsActive)
	PostUsersSetIsActive(ctx context.Context, request PostUsersSetIsActiveRequestObject) (PostUsersSetIsActiveResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PostPullRequestCreate operation middleware
func (sh *strictHandler) PostPullRequestCreate(w http.ResponseWriter, r *http.Request) {
	var request PostPullRequestCreateRequestObject

	var body PostPullRequestCreateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostPullRequestCreate(ctx, request.(PostPullRequestCreateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostPullRequestCreate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostPullRequestCreateResponseObject); ok {
		if err := validResponse.VisitPostPullRequestCreateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostPullRequestMerge operation middleware
func (sh *strictHandler) PostPullRequestMerge(w http.ResponseWriter, r *http.Request) {
	var request PostPullRequestMergeRequestObject

	var body PostPullRequestMergeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostPullRequestMerge(ctx, request.(PostPullRequestMergeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostPullRequestMerge")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostPullRequestMergeResponseObject); ok {
		if err := validResponse.VisitPostPullRequestMergeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostPullRequestReassign operation middleware
func (sh *strictHandler) PostPullRequestReassign(w http.ResponseWriter, r *http.Request) {
	var request PostPullRequestReassignRequestObject

	var body PostPullRequestReassignJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostPullRequestReassign(ctx, request.(PostPullRequestReassignRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostPullRequestReassign")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostPullRequestReassignResponseObject); ok {
		if err := validResponse.VisitPostPullRequestReassignResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetStatsReviewerAssignments operation middleware
func (sh *strictHandler) GetStatsReviewerAssignments(w http.ResponseWriter, r *http.Request) {
	var request GetStatsReviewerAssignmentsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetStatsReviewerAssignments(ctx, request.(GetStatsReviewerAssignmentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStatsReviewerAssignments")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetStatsReviewerAssignmentsResponseObject); ok {
		if err := validResponse.VisitGetStatsReviewerAssignmentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostTeamAdd operation middleware
func (sh *strictHandler) PostTeamAdd(w http.ResponseWriter, r *http.Request) {
	var request PostTeamAddRequestObject

	var body PostTeamAddJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostTeamAdd(ctx, request.(PostTeamAddRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostTeamAdd")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostTeamAddResponseObject); ok {
		if err := validResponse.VisitPostTeamAddResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTeamGet operation middleware
func (sh *strictHandler) GetTeamGet(w http.ResponseWriter, r *http.Request, params GetTeamGetParams) {
	var request GetTeamGetRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTeamGet(ctx, request.(GetTeamGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTeamGet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTeamGetResponseObject); ok {
		if err := validResponse.VisitGetTeamGetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostTeamMassDeactivate operation middleware
func (sh *strictHandler) PostTeamMassDeactivate(w http.ResponseWriter, r *http.Request) {
	var request PostTeamMassDeactivateRequestObject

	var body PostTeamMassDeactivateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostTeamMassDeactivate(ctx, request.(PostTeamMassDeactivateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostTeamMassDeactivate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostTeamMassDeactivateResponseObject); ok {
		if err := validResponse.VisitPostTeamMassDeactivateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUsersGetReview operation middleware
func (sh *strictHandler) GetUsersGetReview(w http.ResponseWriter, r *http.Request, params GetUsersGetReviewParams) {
	var request GetUsersGetReviewRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUsersGetReview(ctx, request.(GetUsersGetReviewRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUsersGetReview")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUsersGetReviewResponseObject); ok {
		if err := validResponse.VisitGetUsersGetReviewResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostUsersSetIsActive operation middleware
func (sh *strictHandler) PostUsersSetIsActive(w http.ResponseWriter, r *http.Request) {
	var request PostUsersSetIsActiveRequestObject

	var body PostUsersSetIsActiveJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostUsersSetIsActive(ctx, request.(PostUsersSetIsActiveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostUsersSetIsActive")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostUsersSetIsActiveResponseObject); ok {
		if err := validResponse.VisitPostUsersSetIsActiveResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xa624bxxV+lcG0QGyAFinZDlD+U2zFFQrLKiUDRQ1BGHHH0ibkLr0XN4JBwJLSJqmM",
	"qPlXGE3cIi9A02JFUyL1CmfeqDgzeyVnV0tRlpv8MeTl7M435/Kdy5wXtG43W7bFLc+l1Re0xRzW5B53",
	"5P/WOWuusCb/o8+dXXxgcLfumC3PtC1apfAzDKEPA+jAqXgFQxhBj0AfzsQRgQGM4Aw6MIRjcUhL1MQ3",
	"nskPlajFmpxWqcdZc1P+XaIOf+abDjdo1XN8XqJufYc3GW7q7bZwses5prVN2+0SfexyZ9nIQvVPOIYe",
	"DMU+9MXXCp/Yh5F4SeAcRhLqCYygKx/34FQcZcDzXe5smsZU4Nrhj1KAS45jOzXutmzL5fiAf8WarYb6",
	"E3/DP+q2gZ9YebS++fmjxyv3aYk2ueuybXzqcNf2nTonlu2Rp7ZvGVICLcduccczuZv6VPqx+vALyi2/",
	"SatP6PrS4sPNpT8tr62v0RJdraX+frhUe7CEeyOOxbW15QcrwX837y2u3F++v7i+FPyqUG6Uxg+fwK3T",
	"WizEJwpavD7+lr31Ba97E+vVCSeXlehD5rr3Oat75nPm8Rp/5nPXm5RFbGo6g5m02BKBrnykTAdG8J7A",
	"UBzAf9HOiTSxDgzQyKALfblCWpR4lWFm0IP3VCOzwMpcDbD/wDn0xR6MYIB+lWHWuEnOnoj1FM+XhtwR",
	"f4M+9NH0Pd50NSqLsDLHYbsTKkk6b3SGIhpy/YZGQUa0wtis277laeTxGs8IffEN9MSe2IcujIg4EHtw",
	"Dj3xba5iYAhDcSj+Wkg5puXxbe4geMv2Nh3OXNfctqZEtlorEXiHgAicQAfOUH3QlyYiXkIPuuKV+B56",
	"oQaH0CPiAI6RTmEk9sQrLaLZ0aQ3IfAWelIa59ARe0qK5xIW4u3ACf4rvslErkE5ZiqTutUcI0PWOota",
	"9RuNTE+P3nf4c5P/JQhlaQkF9kpS5+tFNpI4YzfSz43K3NzCzSn8pUSZ7+3YMoToVtcdjhJZlGd4ajtN",
	"5tEqNZjHb3mmdCvLbzTYFoYLFXY0fOtsz/aFlt9obDpKlllAU2tCDp1Y5XrM891kvHm0urRCSzSILJPx",
	"YsxKxqHoNk7KNNqypNP5BXaztmM7OuPJ1divQVg6udQCqa15LM+hIrqJTM20vE/vaFkqzJ0uzATiJKuA",
	"42NCOgmwyZtbgZtHvvlbhz+lVfqbcpzfloPErIxfeSjf0TltKlPIx54MgSGILNjBhhPgTXdTkmNyuy3b",
	"bnBm5ctR/VYMaCzk6J1SYmcdZsyxp0abJ7sPepakJvLOhR8zrae23Mb0kBjpao2EDkAWpQ02ueWRNe48",
	"N+uc3FjnrkfWmftliXzOGg2yUFm4i3HgOXdcFU7m5ypzFTyF3eIWa5m0Sm/PVeZuo1cyb0dKrtyKyaes",
	"qF+K11YxDIXMMDotGwjJdr0EWd1Ty5UcuOt9Zhu7KsG3PK5ckrVaDbMuv1D+wkVUqWIjwWvUn6caKqMt",
	"59Z8pTKvZZIqXTQM4nLm1HdoO1n/fAz6nJEK9VaRLvHkA1W2yYMtVOanE3jLycpFnlB/AY33NgK5Sr3E",
	"UUUFk3aOohS8PJJM5ljttlZk6ZxqtUZkqXIik8shKvNO5U4BqcUY8/CkS2nN/vAP6KqCqJws5aCjMmuZ",
	"6r0PaqhDhe530+l0vGJPVtBxxb5aI6ZBWMPhzNgl/CvT9dwxXcx0TpQzlqE9IvbEgfguzPHFAfTEvtrJ",
	"bzaZs6tKyEAjMnlfrRHoE+goSaGIZDkp6wQY4E+TCT8cw4gs6HNi6MPJWOEcfV28hA4yM9uWRp+wJ5du",
	"IMoUI8pMtjAhPpSrZ+DDbDfLc5oL+esCZroc81Suh3niWoJihLs1X7m1cGd9fqF6+0717qd/vjJuCjLc",
	"62cn6EqCkt4yEkeyd9knIZxrZivEM05L4777RvpVT7po6L0D6MAgAE1uBE2hMziXjSrVHkLnPSKynkc/",
	"lY0ecXSzuC+GNXhhd6yFL8zgkXbD2IwSRGWol3LS1HculYRcmF4kt/j4Lo1Zpn/3gycTeIZWg9W5sbmF",
	"1unfpVfnwWMfz2nXjKALI3gHo8mA1KEXFs0OTe+0UYA54I2mFyY7eei+XXGoOorozYjvozBJH04xeOuv",
	"N17pmGbK9CeoszFCSOgxSf2o9oAT5BzZ4hRHURdc7MEp9Eh0t/CcNfysVCpaFKdSdWZZtkdCPiK2RRQG",
	"slpTorDse8wyTCOoptK4xL5MXpDwxQGchw3gQZAY9lVaFLQwM6GNXYDE6CybqDqTBCYly8Z6iIeYFsGy",
	"NATqLQb+Owb0Ta7S3opDOJ3oU+qysbP8Q6QudZL3S0Hla7ryiikkGeLZxNsx3UDSV5e+wo/QES/Fgfg2",
	"dqJjFegSPXp0Z+iiXet70aqTfjQZMbPa1jJJHcIAf5YxMotEpKwJHCNGXCKXqTy3p/4ev9nMiarIoW45",
	"lHHcXJDutM01kfUB99bwpZrmnUuFkSyGltAKt8xSHcKLbobUp4tw66M/6HKeU3GQ1tv4XYaGit8nVCmp",
	"J/OyF87knmX0zTIzjPwsZ52z5qJhzJLZRO3JJ6n+mWrIJ1Ke+WRLq0oXG2ad03Yp/6WF9Euf2Vu0vZFq",
	"xNEW21X2U9iJ1yPauuKuiBf0bz+2SLZY/UseXKVnOUiItYCgimQRr1MtiWSnBDoqHFdm60akb/djho/O",
	"/QF7EuOnu2x/IsWtB0TsEUkFHfmFcNbkDPrkRixA8YPYL8MI3gbZIbq4DP2ZF73JUgg1GLK1ZISAlbPI",
	"Gdc/4J7s7MajMk/08ouXlNOjNGiPs5UE/zceND2njJnOT/BW/B16MECdpWPrtbcQX+f3DdFTC4SrAgac",
	"Z4HN1LzExeEpPV8xS6TSKTg5oJJoIBXWu34+50NUyU40WaKZJVnIGuWY101U3M0LDPE+05xbvlMsVPwb",
	"enAiDpC8xD4SF5Gd2j3JeV01iqQd5iGqCMxJl9Gh5q/RoWQVVpa1scqvh+IQ4XfgGN0AhqrvjOkbFmID",
	"WdzckO1oWdGeQEd8h76F7tiFAZyK74PzdG7+AvjhX0m9XXZqbKLD3p9yZkc2BwfipTgU++IQeljU6QkI",
	"fd3FGKgS/rxI+BiXPohWThsQkzOcs4fDZDdLbf9Bm2EbY+Gy4KVB8XprYlJFM6hwiRGLNJhC3a/kDOJq",
	"7ZOcYUNdOZ6Ojqu1T+RkZTAUl9OuKtTtCA1YWmLKgF3uLbuL0aBCdvyUr64lVs8QPRMZ1VPWcHlxG7n0",
	"DEimoi+agbji0OsHwyKTIshNKbJyzRxRhTvlOY8cXSkWan9KlA0/qP4T8m2GZf4y4uf1h8U3xfvOaYL4",
	"WebFnUAFwYDp13AKHXhHEpFyGFzb9fNG+CfooB09exGO9KtYh/VP8EAtTjxIdfESz3/PWcPboe2N9v8C",
	"AAD//zRQOns0MQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
